# copying the dataset

In [2]:
# import os
# import shutil
# import zipfile
# import kagglehub

# # 1️⃣ Current working directory
# cwd = os.getcwd()
# print("Current folder:", cwd)

# # 2️⃣ Download dataset
# path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")
# print("Downloaded dataset path:", path)

# # 3️⃣ Extract to current folder
# if path.endswith(".zip"):
#     with zipfile.ZipFile(path, 'r') as zip_ref:
#         zip_ref.extractall(cwd)
#     print("Dataset extracted to:", cwd)
#     # 4️⃣ Delete original zip
#     os.remove(path)
#     print("Original zip deleted.")
# else:
#     # If it's a folder, copy to current folder
#     dest_path = os.path.join(cwd, "tmdb-movie-metadata")
#     shutil.copytree(path, dest_path)
#     print("Dataset copied to:", dest_path)
#     # 4️⃣ Delete original folder
#     shutil.rmtree(path)
#     print("Original folder deleted.")

# Importing data and creating the data frames

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')
movies.head()
# credits.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
data = movies.merge(credits, on='title')
data.head()
data = data[[ 'title','release_date', 'genres','id', 'keywords', 'overview', 'cast', 'crew' ]]
data.dropna(inplace=True)
data.isnull().sum()
data.info()
data.sample(5)

<class 'pandas.core.frame.DataFrame'>
Index: 4805 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         4805 non-null   object
 1   release_date  4805 non-null   object
 2   genres        4805 non-null   object
 3   id            4805 non-null   int64
 4   keywords      4805 non-null   object
 5   overview      4805 non-null   object
 6   cast          4805 non-null   object
 7   crew          4805 non-null   object
dtypes: int64(1), object(7)
memory usage: 337.9+ KB

,title,release_date,genres,id,keywords,overview,cast,crew
2128,How Stella Got Her Groove Back,1998-08-14,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",33644,"[{""id"": 577, ""name"": ""black people""}, {""id"": 9...","Through good times and bad, Stella and Delilah...","[{""cast_id"": 1, ""character"": ""Stella Payne"", ""...","[{""credit_id"": ""54f39ad5c3a3681deb000435"", ""de..."
4602,Maniac,2012-12-26,"[{""id"": 27, ""name"": ""Horror""}]",103620,"[{""id"": 549, ""name"": ""prostitute""}, {""id"": 286...",As he helps a young artist with her upcoming e...,"[{""cast_id"": 1, ""character"": ""Frank"", ""credit_...","[{""credit_id"": ""52fe4a21c3a36847f81bbac7"", ""de..."
3225,Bright Star,2009-11-05,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",29963,"[{""id"": 5933, ""name"": ""poet""}, {""id"": 10183, ""...","In 1818, high-spirited young Fanny Brawne find...","[{""cast_id"": 2, ""character"": ""Fanny Brawne"", ""...","[{""credit_id"": ""591b3cecc3a3683fb6068bc5"", ""de..."
1942,Carnage,2011-09-16,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",72113,"[{""id"": 1439, ""name"": ""flat""}, {""id"": 1880, ""n...",After 11-year-old Zachary Cowan strikes his cl...,"[{""cast_id"": 3, ""character"": ""Nancy"", ""credit_...","[{""credit_id"": ""5545710c925141586d005150"", ""de..."
4558,Girls Gone Dead,2012-03-28,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...",117942,[],A group of six ex-high school cheerleaders are...,"[{""cast_id"": 24, ""character"": ""Rebecca Foster""...","[{""credit_id"": ""52fe4bc4c3a36847f821312d"", ""de..."

In [5]:
def extract_members(col):
    members = []
    for item in eval(col):
        members.append(item['name'])
    return members

In [6]:
data['genres'] = data['genres'].apply(extract_members)
data['keywords'] = data['keywords'].apply(extract_members)

In [7]:
data.head(5)

,title,release_date,genres,id,keywords,overview,cast,crew
0,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,2015-10-26,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,2012-03-07,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
def top3Cast(col):
    cast = []
    count = 1
    for item in eval(col):
        cast.append(item['name'])
        count += 1
        if count > 3:
            break
    return cast

data['cast'] = data['cast'].apply(top3Cast)
data.head(5)

,title,release_date,genres,id,keywords,overview,cast,crew
0,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,2015-10-26,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,2012-03-07,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
def extract_director(col):
    for item in eval(col):
        if item['department'] == 'Directing':
            return item['name']
    return np.nan

data['director'] = data['crew'].apply(extract_director)
data.sample(5)

,title,release_date,genres,id,keywords,overview,cast,crew,director
3009,Twilight Zone: The Movie,1983-06-24,"[Drama, Fantasy, Horror, Science Fiction, Thri...",15301,"[nazis, anthology, remake, twilight zone]",Four directors collaborated to remake four epi...,"[Albert Brooks, Vic Morrow, John Larroquette]","[{""credit_id"": ""52fe464c9251416c75073d33"", ""de...",Steven Spielberg
4646,Love and Other Catastrophes,1996-08-01,"[Comedy, Romance]",76996,"[independent film, woman director]",A day in the life of two film-school students ...,"[Matt Day, Matthew Dyktynski, Alice Garner]","[{""credit_id"": ""52fe4956c3a368484e12665f"", ""de...",Emma-Kate Croghan
349,The Secret Life of Walter Mitty,2013-12-18,"[Adventure, Comedy, Drama, Fantasy]",116745,"[himalaya, photographer, magazine, iceland, da...",A timid magazine photo manager who lives life ...,"[Ben Stiller, Kristen Wiig, Patton Oswalt]","[{""credit_id"": ""52fe4b9dc3a36847f820c10b"", ""de...",Ben Stiller
1371,Cape Fear,1991-11-15,"[Crime, Thriller]",1598,"[prison, child abuse, rape, small town, daught...",Sam Bowden is a small-town corporate attorney....,"[Robert De Niro, Nick Nolte, Jessica Lange]","[{""credit_id"": ""52fe4303c3a36847f8033dd9"", ""de...",Martin Scorsese
3786,The Loss of Sexual Innocence,1999-04-29,[Drama],15059,[],The story of the sexual development of a filmm...,"[Julian Sands, Saffron Burrows, Justin Chadwick]","[{""credit_id"": ""554cc8ebc3a3685e55005358"", ""de...",Mike Figgis

In [10]:
data.drop(['crew'], axis=1, inplace=True)
data.head(5)

,title,release_date,genres,id,keywords,overview,cast,director
0,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,Spectre,2015-10-26,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes
3,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,John Carter,2012-03-07,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton

In [11]:
data['overview'] = data['overview'].apply(lambda x: x.split(' '))
data.head(5)

,title,release_date,genres,id,keywords,overview,cast,director
0,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,Spectre,2015-10-26,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes
3,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,John Carter,2012-03-07,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton

In [12]:
# data['director']= data['director'].apply(lambda x: x.replace(' ',''))
data.cast[0]
data['cast']=data['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
data.head(5)
data['director'] = data['director'].fillna('')
data['director'] = data['director'].apply(lambda x: [x.replace(" ", "")])
data['keywords'] = data['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
data.head(5)

,title,release_date,genres,id,keywords,overview,cast,director
0,Avatar,2009-12-10,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,Spectre,2015-10-26,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,John Carter,2012-03-07,"[Action, Adventure, Science Fiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [13]:
data['genres'] = data['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
data.sample(5)

,title,release_date,genres,id,keywords,overview,cast,director
3664,Farce of the Penguins,2006-12-01,"[Comedy, Documentary]",12486,"[penguin, balzen, antarctic]","[In, this, spoof, of, ""March, of, the, Penguin...","[SamuelL.Jackson, JimBelushi, WhoopiGoldberg]",[BobSaget]
3231,Yeh Jawaani Hai Deewani,2013-05-31,[Romance],185008,[],"[Yeh, Jawaani, Hai, Deewani, features, two, po...","[RanbirKapoor, DeepikaPadukone, KalkiKoechlin]",[AyanMukherjee]
4806,"Signed, Sealed, Delivered",2013-10-13,"[Comedy, Drama, Romance, TVMovie]",231617,"[date, loveatfirstsight, narration, investigat...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
3509,Don McKay,2009-04-24,"[Crime, Mystery, Thriller]",35689,[independentfilm],"[Everything, appears, off-kilter, when, a, man...","[ThomasHadenChurch, ElisabethShue, MelissaLeo]",[JakeGoldberger]
3015,The Outsiders,1983-03-25,"[Crime, Drama]",227,"[streetgang, children'shome, comingofage, gang...","[When, two, poor, greasers,, Johnny,, and, Pon...","[MattDillon, RalphMacchio, C.ThomasHowell]",[FrancisFordCoppola]

In [14]:
data['tags']= data['overview'] + data['genres'] + data['keywords'] + data['cast'] + data['director']
data.head(5)

,title,release_date,genres,id,keywords,overview,cast,director,tags
0,Avatar,2009-12-10,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,2007-05-19,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,2015-10-26,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,2012-07-16,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,John Carter,2012-03-07,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [15]:
data['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [16]:
data.drop(['overview', 'genres', 'keywords', 'cast', 'director','release_date'], axis=1, inplace=True)
data.head(5)

,title,id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."

In [17]:
" ".join(data['tags'][0]).lower()
data['tags']=data['tags'].apply(lambda x: " ".join(x).lower())
data.head()
data['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [18]:
data['title']=data['title'].apply(lambda x: x.lower())
data.head()

,title,id,tags
0,avatar,19995,"in the 22nd century, a paraplegic marine is di..."
1,pirates of the caribbean: at world's end,285,"captain barbossa, long believed to be dead, ha..."
2,spectre,206647,a cryptic message from bond’s past sends him o...
3,the dark knight rises,49026,following the death of district attorney harve...
4,john carter,49529,"john carter is a war-weary, former military ca..."

# NLP -> nltk library

In [19]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stemming(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [20]:
data['tags'] = data['tags'].apply(stemming)

In [21]:
data['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(data['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4805, 5000))

In [23]:
cv.get_feature_names_out()[:100]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940', '1944', '1950', '1950s', '1960', '1960s', '1970',
       '1970s', '1974', '1976', '1980', '1985', '1990', '1999', '19th',
       '19thcenturi', '20', '200', '2003', '2009', '20th', '21st', '23',
       '24', '25', '30', '300', '3d', '40', '50', '500', '60', '70', '80',
       'aaron', 'aaroneckhart', 'abandon', 'abduct', 'abigailbreslin',
       'abil', 'abl', 'aboard', 'abov', 'abus', 'academ', 'academi',
       'accept', 'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'account', 'accus', 'ace', 'achiev', 'acquaint',
       'act', 'action', 'actionhero', 'activ', 'activist', 'activities',
       'actor', 'actress', 'actual', 'ad', 'adam', 'adamsandl',
       'adamshankman', 'adapt', 'add', 'addict', 'adjust', 'admir',
       'admit', 'adolesc', 'adopt', 'ador', 'adrienbrodi'], dtype=object)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [25]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4805, 4805))

In [26]:
def recommend(movie):
    movie_index = data[data['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    for i in movies_list:
        print(data.iloc[i[0]].title)
recommend('meet dave')

the hitchhiker's guide to the galaxy
escape from planet earth
home
planet 51
aliens in the attic

In [27]:
recommend('the dark knight rises')

the dark knight
batman returns
batman
batman forever
batman begins

In [28]:
import pickle
pickle.dump(data, open('movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [29]:
import joblib
joblib.dump(similarity, 'similarities.joblib',compress=3)

['similarities.joblib']